### PR TITLE
Update Google Analytics snippet to show cookie banner when needed

### PR DESCRIPTION
**Pull request by barrycburton**
Targeted this PR at develop since that seems to be the default branch and it has the latest changes. Should we merge develop into master and make master the default branch on Github though? Would be less surprising, I think.

Do we have a staging environment to test Grav template changes? This is a very simple change that I'm reasonably confident will work, but all the same I have not been able to test yet.

What does deploying Grav template changes look like, anway?

### CODE REVIEW

**Comment by barrycburton** [comment]
[Cannot set cookie preferences](https://trello.com/c/MNRCADPf/865-cannot-set-cookie-preferences)

**Comment by blantow1** [comment]
Currently the training grav site is not configured to even use this twig. I can enable the analytics within the config yaml and update the wiki accordingly but it sounds as though there is a significant grav update. Will coordinate with Barry this week to merge and update as required.

**Comment by blantow1** [comment]
Added GA Tag to learn2.yaml so the theme will begin using GA - checked locally and had no errors in running.

**Review by blantow1 — COMMENTED** [review]
Functionally fine on my local machine - cannot speak to code.

**Pull request merged**
